
# app.yaml for Google App Engine deployment

runtime: nodejs20  # Updated to Node.js 20 LTS runtime

env_variables:
  API_BASE_URL: "https://pratham-respos-testbe-v34.achyutlabs.cloud/api"
  VERSION_NO: "3.4.0"
  BASE_URL: "https://pratham-respos-testbe-v34.achyutlabs.cloud"
  VITE_EXTERNAL_API_URL: "https://pratham-respos-testbe-v34.achyutlabs.cloud/api"

handlers:
  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: dist/\1
    upload: dist/(.*\..+)$
    secure: always

  # Catch all handler to index.html
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always

# Standard App Engine deployment settings
instance_class: F2
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 3
  min_pending_latency: 1000ms
  max_pending_latency: 10000ms
  max_instances: 10

# Build steps before deployment
build_steps:
  - name: node:20
    entrypoint: npm
    args: ['install']
  - name: node:20
    entrypoint: npm
    args: ['run', 'build']
